### ISSUE TITLE
어떤 스타일 언어 사용할 것인지 결정

### ISSUE THREAD

**Issue by enif-lee** [think-ui/think#1]
아래는 스타일 언어 목록입니다. 어떤 스타일언어를 사용하는 것이 가장 좋을지 의견을 나눠봅시다.

- SASS
- LESS
- PostCSS
- Stylus

**Comment by enif-lee** [comment]
CC. @choi4450

**Comment by enif-lee** [comment]
구냥 SASS 로 할께요~

**Comment by choegyumin** [comment]
점유율 때문에 sass해야됨...
